const strategies = ['不限','股票策略','固定收益策略','CTA策略','组合基金策略','ETF套利策略','类现金策略','期权策略','多策略','宏观策略','联结基金','其他'];
const funds = [
  ['XXX0012','XXX灵活配置12号','美市数据源','股票策略','XXX财富管理有限公司','2027-04-15','1.4840','2.0760','6.00%','-4.70%','1.80'],
  ['XXX0012','XXX灵活配置12号','托管部自有数据','股票策略','XXX财富管理有限公司','2028-05-15','1.5310','2.1590','6.60%','-5.00%','1.89'],
  ['XXX0012','XXX灵活配置12号','火富牛','股票策略','XXX财富管理有限公司','2029-06-15','1.5780','2.2420','7.20%','-5.30%','1.98'],
  ['XXX0012','XXX灵活配置12号','机构部','股票策略','XXX财富管理有限公司','2030-07-15','1.6250','2.3250','7.80%','-5.60%','2.07'],
  ['XXX0011','XXX绝对收益11号','托管部自有数据','固定收益策略','XXX基金管理有限公司','2026-03-15','1.4370','1.9930','5.40%','-4.40%','1.71'],
  ['XXX0010','XXX宏观对冲10号','机构部','宏观策略','XXX投资管理有限公司','2025-02-15','1.3900','1.9100','4.80%','-4.10%','1.62'],
  ['XXX0009','XXX均衡配置9号','火富牛','组合基金策略','XXX私募基金管理有限公司','2024-01-15','1.3430','1.8270','4.20%','-3.80%','1.53'],
  ['XXX0008','XXX套利机会8号','美市数据源','ETF套利策略','XXX资产管理有限公司','2023-08-15','1.2960','1.7440','3.60%','-3.50%','1.44'],
  ['XXX0007','XXX红利精选7号','托管部自有数据','股票策略','XXX资本管理有限公司','2022-07-15','1.2490','1.6610','3.00%','-3.20%','1.35'],
  ['XXX0006','XXXCTA趋势6号','机构部','CTA策略','XXX投资咨询有限公司','2021-06-15','1.2020','1.5780','2.40%','-2.90%','1.26']
];
const selectedSources = new Set(['托管部自有数据','火富牛','机构部','美市数据源']); const selectedStrategies = {}; let isFilterOpen = true; let currentPage = 1; const pageSize = 8; let pagerVm;
function renderStrategies() { const area=document.getElementById('strategyRows'); area.innerHTML=''; [...selectedSources].forEach(source=>{ const row=document.createElement('div'); row.className='strategy-row'; row.innerHTML='<span class="strategy-label">'+source+'投资策略：</span>'+strategies.map((s,i)=>'<span class="option '+((selectedStrategies[source]||[]).includes(s)||(i===0&&!selectedStrategies[source]?.length)?'active':'')+'" data-source="'+source+'" data-strategy="'+s+'">'+s+'</span>').join(''); area.appendChild(row); }); bindOptions(); }
function bindOptions() { document.querySelectorAll('.source-row .option').forEach(el=>el.onclick=()=>{ const source=el.dataset.source; selectedSources.has(source)?selectedSources.delete(source):selectedSources.add(source); renderAll(); }); document.querySelectorAll('.strategy-row .option').forEach(el=>el.onclick=()=>{ const source=el.dataset.source, strategy=el.dataset.strategy; if(strategy==='不限') selectedStrategies[source]=[]; else { const list=selectedStrategies[source]||[]; selectedStrategies[source]=list.includes(strategy)?list.filter(x=>x!==strategy):list.concat(strategy); } renderAll(); }); }
function getFilteredFunds() { const key=document.getElementById('nameKeyword').value.trim().toLowerCase(), manager=document.getElementById('managerKeyword').value.trim().toLowerCase(); return funds.filter(f=>selectedSources.has(f[2])&&(!key||(f[0]+f[1]).toLowerCase().includes(key))&&(!manager||f[4].toLowerCase().includes(manager))&&(!(selectedStrategies[f[2]]||[]).length||(selectedStrategies[f[2]]||[]).includes(f[3]))); }
function renderTable() { const rows=getFilteredFunds(); const totalPages=Math.max(1,Math.ceil(rows.length/pageSize)); if(currentPage>totalPages) currentPage=totalPages; const visibleRows=rows.slice((currentPage-1)*pageSize,currentPage*pageSize); document.getElementById('fundRows').innerHTML=visibleRows.map((f,i)=>'<tr><td>'+ ((currentPage-1)*pageSize+i+1) +'</td><td>'+f[0]+'</td><td><span class="link" onclick="showReport(\''+f[1]+'\')">'+f[1]+'</span></td><td>'+f[2]+'</td><td>'+f[3]+'</td><td>'+f[4]+'</td><td>'+f[5]+'</td><td>2026-08-14</td><td>'+f[6]+'</td><td>'+f[7]+'</td><td class="positive">'+f[8]+'</td><td class="negative">'+f[9]+'</td><td class="positive">'+f[10]+'</td></tr>').join(''); if (pagerVm) { pagerVm.total=rows.length; pagerVm.currentPage=currentPage; } document.getElementById('selectedTags').innerHTML=[...selectedSources].map(s=>'<span class="tag">数据来源：'+s+' <b onclick="removeSource(\''+s+'\')">×</b></span>').join(''); }
function renderAll(){ renderStrategies(); renderTable(); } function removeSource(s){ selectedSources.delete(s); currentPage=1; renderAll(); } function queryFunds(){ currentPage=1; renderTable(); notify('已按当前条件展示静态测试数据'); }
function resetFilters(){ document.getElementById('nameKeyword').value=''; document.getElementById('managerKeyword').value=''; document.getElementById('endDate').value='2026-08-14'; selectedSources.clear(); ['托管部自有数据','火富牛','机构部','美市数据源'].forEach(s=>selectedSources.add(s)); Object.keys(selectedStrategies).forEach(k=>delete selectedStrategies[k]); currentPage=1; renderAll(); notify('已重置为默认测试条件'); }
function toggleFilters(){ isFilterOpen=!isFilterOpen; document.getElementById('filterBody').style.display=isFilterOpen?'block':'none'; document.getElementById('toggleButton').textContent=isFilterOpen?'收起筛选 ▲':'展开筛选 ▼'; }
function download(name,text){ const a=document.createElement('a'); a.href=URL.createObjectURL(new Blob(['\ufeff'+text],{type:'text/csv;charset=utf-8'})); a.download=name; a.click(); URL.revokeObjectURL(a.href); } function exportFunds(){ download('产品筛选-静态测试数据.csv','产品代码,产品名称,数据来源,投资策略\n'+funds.map(f=>f.slice(0,4).join(',')).join('\n')); } function exportReport(){ download('周频净值报告-静态测试数据.csv','产品代码,产品名称,数据来源\nXXX0001,XXX稳健增长1号,托管部自有数据'); }
function showReport(name){ document.getElementById('reportName').textContent=name; document.getElementById('filterPage').style.display='none'; document.getElementById('reportPage').style.display='block'; window.scrollTo(0,0); } function showFilterPage(){ document.getElementById('reportPage').style.display='none'; document.getElementById('filterPage').style.display='block'; } function notify(msg){ window.alert(msg); }
pagerVm = new Vue({ el:'#staticPager', data:{ currentPage:1, pageSize, total:funds.length }, methods:{ changePage(page){ currentPage=page; this.currentPage=page; renderTable(); } } });
document.querySelectorAll('.filter-line > .option,.range > .option').forEach(el=>el.onclick=()=>el.classList.toggle('active')); renderAll();
